kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/plotnikau/tube2pod

steps:
- name: build
  image: golang
  commands:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - CGO_ENABLED=0 GOOS=linux go build -o tube2pod main.go


- name: publish_image
  image: plugins/docker
  settings:
    auto_tag: true
    dockerfile: docker/Dockerfile.ci
    repo: plotnikau/tube2pod
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag
